### ISSUE TITLE
departments/view/1 map

### ISSUE THREAD

**Issue by rrd108** [rrd108/ganesh#15]
show a map of covered activities

**Comment by ifjuszalaimihaly** [comment]
The length of the activities are based on hours? What is the smallest, atomic time interval? The users can register to an activity just whole hours long?

**Comment by ifjuszalaimihaly** [comment]
The models, which have start and end parameters, should have an parent class, interface or trait?

**Comment by rrd108** [comment]
a táblázatban annyi sor legyen minimum ahány a manpower igény
ha több jelentkező van akkor azoknak egy másik style
a be nem töltött tábla cellák css class
usernevek vissza
túljelentkezés külön style jelölés
színek: https://foundation.zurb.com/sites/docs/label.html
